### ISSUE TITLE
EMSA Net Evaluation Error

### ISSUE THREAD

**Issue by farishajdarpasic** [TUI-NICR/EMSANet#11]
Hello, I have issue running EMSANet. I followed all steps, tried creating both environments (with cuda11.7 and cuda11.3), I downloaded and extracted datasets models using your processing repo, but when I run any model I get sometimes this error:

Get model and dataset
Loading (pretrained) weights from: './trained_models/sunrgbd/r34_NBt1D_pre.pth'.
-> Epoch: 473
Computing class weights for 'semantic' ...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5285/5285 [00:03<00:00, 1451.16it/s]
Run validation only
Validation 1/4 (realsense):   0%|                                                                                                                                                   | 0/36 [00:00<?, ?it/s]
Killed

And sometimes this error:
  Traceback (most recent call last):
    File "main.py", line 683, in <module>
      main()
    File "main.py", line 481, in main
      for batch in tqdm(valid_dataloader,
    File "/home/faris/miniconda3/envs/emsanet/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
      for obj in iterable:
    File "/home/faris/miniconda3/envs/emsanet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
      data = self._next_data()
    File "/home/faris/miniconda3/envs/emsanet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _next_data
      idx, data = self._get_data()
    File "/home/faris/miniconda3/envs/emsanet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1272, in _get_data
      success, data = self._try_get_data()
    File "/home/faris/miniconda3/envs/emsanet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1133, in _try_get_data
      raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
  RuntimeError: DataLoader worker (pid(s) 8229) exited unexpectedly

Can you please explain me what is problem here?

Sample Inference works (but not Dataset Inference)

**Comment by danielS91** [comment]
'Killed' sounds like an OOM issue?
